// layout.tsx (server-side layout)
import "./globals.css";
import Sidebar from "../components/derived/SideBar";
import ClientSessionProvider from '@/app/(auth)/ClientSessionProvider' // Import the client component
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/derived/Footer";
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "@/components/ui/resizable";
import Header from "@/components/derived/Header";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the type for the props
interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <ClientSessionProvider>
        <body >
        <main className="flex flex-1">
            <ResizablePanelGroup direction="horizontal" className="w-full">
              <ResizablePanel
                defaultSize={20} 
                className="bg-gray-200"
              >
                <Sidebar />
              </ResizablePanel>

              <ResizableHandle className="bg-gray-300 w-2" />

              <ResizablePanel
                defaultSize={80}
                className="bg-white flex flex-col"
              >
                <div className="flex-1 p-4">{children}</div>
              </ResizablePanel>
            </ResizablePanelGroup>
        </main>
        <Toaster/>
        <Footer/>
        </body>
      </ClientSessionProvider>
    </html>
  );
}


    